Repository DARIAEngineering/dcaf_case_management, pull requests merged in 2019-02, with the labels that each got.

#1594 Translate Spanish event strings (and move them out of the model)
  app/helpers/events_helper.rb
  app/models/event.rb
  config/locales/en.yml
  config/locales/es.yml
  test/helpers/events_helper_test.rb
  test/models/event_test.rb
Labels: ready for translation review

#1601 Translate tooltip helper text
  app/helpers/tooltips_helper.rb
  config/locales/en.yml
  config/locales/es.yml
Labels: ready for translation review

#1599 Spanish Patient Part 1
  app/helpers/patients_helper.rb
  app/views/patients/_patient_information.html.erb
  config/locales/en.yml
  config/locales/es.yml
  test/helpers/patients_helper_test.rb
Labels: reviewed

#1595 Add clinic finder gestation filter
  app/controllers/clinicfinders_controller.rb
  app/helpers/clinicfinders_helper.rb
  app/models/clinic.rb
  app/models/concerns/last_menstrual_period_measureable.rb
  app/views/clinicfinders/_search_form.html.erb
  app/views/clinicfinders/search.js.erb
  app/views/patients/_abortion_information.html.erb
  test/helpers/clinicfinders_helper_test.rb
  test/models/clinic_test.rb
Labels: ready for review

#1610 Patiente parte 2
  app/helpers/calls_helper.rb
  app/views/patients/_abortion_information.html.erb
  app/views/patients/_call_log.html.erb
  app/views/patients/_change_log.html.erb
  config/locales/en.yml
  config/locales/es.yml
Labels: ready for translation review

#1618 Bootstrap sass Take 2!
  Gemfile
  Gemfile.lock
Labels: ready for review

#1607 External Pledges Spanish Translation
  app/helpers/external_pledges_helper.rb
  app/views/external_pledges/_edit.html.erb
  app/views/external_pledges/_new.html.erb
  config/locales/en.yml
  config/locales/es.yml
  test/helpers/external_pledges_helper_test.rb
Labels: ready for translation review

#1608 Clinic Locator Spanish Translation
  .circleci/config.yml
  app/views/clinicfinders/_search_form.html.erb
  config/locales/en.yml
  config/locales/es.yml
Labels: ready for review, ready for translation review
