Repository DARIAEngineering/dcaf_case_management, pull requests merged in 2021-06, with the labels that each got.

#2207 Adds a clinic's city & state to the clinic dropdown
  app/helpers/patients_helper.rb
  config/locales/en.yml
  config/locales/es.yml
  test/helpers/patients_helper_test.rb
  test/system/filter_medicaid_clinics_test.rb
  test/system/filter_naf_clinics_test.rb
Labels: feature

#2242 actually remove mongo session store
  Gemfile.lock
Labels: dependencies

#2243 Fix user search bug causing errors if no results are found
  app/views/users/search.js.erb
Labels: feature

#2240 remove kaminari-mongoid gem
  Gemfile
  Gemfile.lock
Labels: dependencies

#2248 Converts clinicfinder controller to postgres
  app/controllers/clinicfinders_controller.rb
Labels: feature

#2218 Accountant dashboard - clinic filtering
  app/controllers/accountants_controller.rb
  app/views/accountants/_search_form.html.erb
  config/locales/en.yml
  config/locales/es.yml
  test/controllers/accountants_controller_test.rb
  test/system/accountant_workflow_test.rb
Labels: feature

#2257 Fix - Updating update_pledge_sent_by_sent_at save for consistency
  app/models/patient.rb
  test/system/data_entry_test.rb
Labels: ready for review
