Repository DARIAEngineering/dcaf_case_management, pull requests merged in 2021-07, with the labels that each got.

#2220 Update accountant information and UX
  app/controllers/accountants_controller.rb
  app/controllers/dashboards_controller.rb
  app/javascript/styles/tables.scss
  app/models/concerns/patient_searchable.rb
  app/views/accountants/_table_content.html.erb
  app/views/accountants/_table_content_row.html.erb
  app/views/accountants/index.html.erb
  app/views/accountants/search.js.erb
  config/locales/en.yml
  config/locales/es.yml
  test/models/patient/searchable_test.rb
  test/system/accountant_workflow_test.rb
  test/system/record_lookup_test.rb
Labels: bug, enhancement, feature, frontend

#2259 update sqreen gem
  Gemfile.lock
Labels: dependencies

#2253 bump papertrail gem to v12
  Gemfile
  Gemfile.lock
Labels: dependencies

#2264 Allow patients with sent pledges to be marked urgent again
  app/models/concerns/urgency.rb
  test/models/patient_test.rb
  test/system/submit_pledge_test.rb
Labels: feature

#2308 pin bootstrap gem to < 5
  Gemfile
  Gemfile.lock
Labels: dependencies

#2299 Upgrade node and ruby
  .circleci/config.yml
  .docker/Dockerfile
  .gitignore
  .nvmrc
  .ruby-version
  Gemfile
  Gemfile.lock
  docs/SETUP.md
  package.json
  yarn.lock
Labels: dependencies
